name: Context example

on: [push]

jobs:
    my-context:
        runs-on: ubuntu-latest
        steps:
            - name: "using github.action context"
              run: | 
                echo "Action! $MY_ACTION "
                echo "Actor!  $MY_ACTOR"
              env:
                MY_ACTION: ${{github.action}}  
                MY_ACTOR: ${{ github.actor}}