name: running hello from other repo
on: ['push']
jobs:
    my-job:
        runs-on: ubuntu-latest
        name: a job to say hello
        steps:
            - name: say heelo to me
              id: hello
              uses: deep0304/hello@1.2.1
              with:
                name: "ghost"
            - name: get the output
              run: echo "greeting is the ${{steps.hello.outputs.greeting}}"  
    