name: 'dependent jobs '
'on':
  - push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: printing the namaste
        run: echo "namaste"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: printing the ji ghost
        run: echo "ji Ghost"
  job3:
    runs-on: ubuntu-latest
    steps:
        - name: "independent job of the other two "
          run: echo " rider ji"      
