name: Greetings

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main 
  workflow_dispatch:    
    inputs:
      name:
        description: 'Enter the name of the user'
        required: true
        type: string
      greeting: 
        description: 'type of greeting'
        required: true
        type: string
      data:
        description: 'Base64 encoded content'
        required: false
        type: string  


  # schedule:
  #   - cron: '*/1 * * * *'     

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Decode the file content
        run: |
          echo "${{ inputs.data}}" |  base64 --decode > ./decoded_file.txt
      - name: Displaying greeting
        run: |
          echo "${{ inputs.greeting}} , ${{ inputs.name}}!"
      - name: Display file content
        run: |
          echo "contents pf the file:"
          cat ./decoded_file.txt     


