name: windows runner

on:
  push:
    branches:
        - main

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: choco install dotnetcore-sdk
        shell: powershell
      - name: 'Compile run and c# program'
        run: |
          Add-Content -Path "Hello.cs" -Value @"
          using System;
              public class Hello
              {
                  public static void Main()
                  {
                      Console.Write("Hello, from windows runner Ghost");
                  
                  }
              }
              "@
          dotnet new console --force --no-restore
          Move-Item -Path "Hello.cs" -Destination "Program.cs" -Force
          dotnet run
        shell: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.EXE -command ". '{0}'"
